version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres:13
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5433"
    restart: unless-stopped

volumes:
    postgres: